# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6.3'

- script: |
    gem update --system '2.0.1'
    gem install jekyll
    gem install bundler --version '2.0.1'
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec jekyll algolia
  displayName: 'bundle exec jekyll algolia'
  env: { ALGOLIA_API_KEY: $(ALGOLIA_API_KEY) }
